### ISSUE TITLE
[STORY][ARGOCD] - TEST FOR HOMERUN HELM CHARTS

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/docs#10]
DO THE WHOLE STORY ON A DEV MACHINE UNTIL CREATE HELM BASED APPLICATION

![Image](https://github.com/user-attachments/assets/672d7b56-6db6-441c-8ee6-336bf79c820f)

CREATE THREE APPLICATIONS FOR HOMERUN:

```
kubectl apply -f - <<EOF
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homerun-redis-stack
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: hoemrun
    server: ${SERVER_URL}
  source:
    path: ''
    repoURL: 
    targetRevision:
    chart:
    helm:
      values: |
        #....

# ...
```

https://github.com/stuttgart-things/stuttgart-things/blob/main/helm/homerun-base-stack/homerun-base.yaml

  - name: homerun-redis-stack
  - name: homerun-generic-pitcher
  - name: homerun-text-catcher

you are not commiting them to git so if you are working with secrets- its ok for now to give them to the application manifest

**Comment by andre-ebert-sva** [comment]
homerun-redis-stack
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homerun-redis-stack
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: homerun
    server: https://10.31.103.47:34297
  source:
    path: ''
    repoURL: ghcr.io
    targetRevision: v0.6.0
    chart: stuttgart-things/homerun
    helm:
      values: |
        serviceType: ClusterIP
        enabled: true
        password:
        storageSize: 4Gi
        port: 6379
        serviceName: homerun-redis-stack-headless
        persistenceEabled: true
        storageClass: local-path
        stream: homerun
        searchIndex: homerun
        hostname: 10.31.103.47
        domain: nip.io
        issuerKind: ClusterIssuer
        issuerName: selfsigned
  sources: []
  project: maverick
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: null

```

homerun-generic-pitcher
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homerun-generic-pitcher
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: homerun
    server: https://10.31.103.47:34297
  source:
    path: ''
    repoURL: ghcr.io
    targetRevision: v0.6.0
    chart: stuttgart-things/homerun
    helm:
      values: |
        enabled: true
        name: homerun-generic-pitcher
        port: 4000
        apiPath: generic
        token:
  sources: []
  project: maverick
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: null

```

homerun-text-catcher
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homerun-text-catcher
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: homerun
    server: https://10.31.103.47:34297
  source:
    path: ''
    repoURL: ghcr.io
    targetRevision: v0.6.0
    chart: stuttgart-things/homerun
    helm:
      values: |
        enabled: true
        name: homerun-text-catcher
        logging: terminal
  sources: []
  project: maverick
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: null

```

**Comment by patrick-hermann-sva** [comment]
this cannot work! habe a look at the major key. your application was green because based on the values no sub chart of the umbrella chart homerun was enabled - green but nothing was deployed..

![Image](https://github.com/user-attachments/assets/e1dccc2e-e313-4542-aec1-64bfc8b500fd)

**Comment by patrick-hermann-sva** [comment]
@andre-ebert-sva test the vault plugin with your homerun applicatiosn. shortend example below!

```yaml
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            text-catcher:
              enabled: true
            redis-stack:
              enabled: true
              global:
                redis:
                  password: <path:apps/data/homerun#redisPassword>
              master:
                persistence:
                  enabled: true
                  storageClass: nfs4-csi
              replica:
                persistence:
                  enabled: true
                  storageClass: nfs4-csi
```
